[2024-11-13T22:53:29.146+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-13T22:53:29.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brew-dag.silver_gold scheduled__2024-11-12T07:00:00+00:00 [queued]>
[2024-11-13T22:53:29.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brew-dag.silver_gold scheduled__2024-11-12T07:00:00+00:00 [queued]>
[2024-11-13T22:53:29.177+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-13T22:53:29.195+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): silver_gold> on 2024-11-12 07:00:00+00:00
[2024-11-13T22:53:29.207+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-13T22:53:29.209+0000] {standard_task_runner.py:72} INFO - Started process 335 to run task
[2024-11-13T22:53:29.209+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brew-dag', 'silver_gold', 'scheduled__2024-11-12T07:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/brew-dag.py', '--cfg-path', '/tmp/tmp3w105xtv']
[2024-11-13T22:53:29.210+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask silver_gold
[2024-11-13T22:53:29.267+0000] {task_command.py:467} INFO - Running <TaskInstance: brew-dag.silver_gold scheduled__2024-11-12T07:00:00+00:00 [running]> on host 453aae92f04c
[2024-11-13T22:53:29.366+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nelsonlsn@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brew-dag' AIRFLOW_CTX_TASK_ID='silver_gold' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-12T07:00:00+00:00'
[2024-11-13T22:53:29.370+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-13T22:53:29.371+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-13T22:53:29.371+0000] {logging_mixin.py:190} INFO - Current task name:silver_gold state:running start_date:2024-11-13 22:53:29.164530+00:00
[2024-11-13T22:53:29.372+0000] {logging_mixin.py:190} INFO - Dag name:brew-dag and current dag run status:running
[2024-11-13T22:53:29.373+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-13T22:53:29.377+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/brew-dag.py", line 64, in silver_gold
    df_sl = pd.read_parquet('/opt/airflow/datalake/datalake/silver/breweries', engine='pyarrow')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/datalake/datalake/silver/breweries'
[2024-11-13T22:53:29.397+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-13T22:53:29.398+0000] {logging_mixin.py:190} INFO - Task start:2024-11-13 22:53:29.164530+00:00 end:2024-11-13 22:53:29.397265+00:00 duration:0.232735
[2024-11-13T22:53:29.399+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): silver_gold> dag:<DAG: brew-dag> dagrun:<DagRun brew-dag @ 2024-11-12 07:00:00+00:00: scheduled__2024-11-12T07:00:00+00:00, state:running, queued_at: 2024-11-13 22:47:20.279583+00:00. externally triggered: False>
[2024-11-13T22:53:29.400+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/datalake/datalake/silver/breweries'
[2024-11-13T22:53:29.400+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=brew-dag, task_id=silver_gold, run_id=scheduled__2024-11-12T07:00:00+00:00, execution_date=20241112T070000, start_date=20241113T225329, end_date=20241113T225329
[2024-11-13T22:53:29.427+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-11-13T22:53:29.428+0000] {email.py:272} INFO - Email alerting: attempt 1
[2024-11-13T22:53:31.630+0000] {email.py:283} INFO - Sent an alert email to ['nelsonlsn@gmail.com']
[2024-11-13T22:53:34.192+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: failure_email
[2024-11-13T22:53:34.199+0000] {email.py:272} INFO - Email alerting: attempt 1
[2024-11-13T22:53:35.931+0000] {email.py:283} INFO - Sent an alert email to ['nelsonlsn@gmail.com']
[2024-11-13T22:53:38.208+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-13T22:53:38.209+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 60 for task silver_gold ([Errno 2] No such file or directory: '/opt/airflow/datalake/datalake/silver/breweries'; 335)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/brew-dag.py", line 64, in silver_gold
    df_sl = pd.read_parquet('/opt/airflow/datalake/datalake/silver/breweries', engine='pyarrow')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/datalake/datalake/silver/breweries'
[2024-11-13T22:53:38.273+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-13T22:53:38.283+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
